server:
  port: 6060


spring:
  application:
    name: product
  redis:
    port: 6379
    host: localhost

  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    service-url:
      bj-zone1: http://localhost:8761/eureka


