server:
  port: 8762


eureka:
  client:
    service-url:
        bj-zone1: http://localhost:8761/eureka
        bj-zone3: http://localhost:8763/eureka

  instance:
    metadata-map:
      zone: bj-zone2